export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const PHASE_REPOSITORY = 'PHASE_REPOSITORY';
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
export const COMPANY_TASK_REPOSITORY = 'COMPANY_TASK_REPOSITORY';
