name: Notify on GitHub Action Run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["GraphQL Microservice"]
    types: [completed]

jobs:

   build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 85958/graphql-microservice:latest

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/
            docker-compose -f docker-compose-microservice.yml pull graphql-microservice
            docker-compose -f docker-compose-microservice.yml stop graphql-microservice
            docker-compose -f docker-compose-microservice.yml up -d
            exit

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO }}
          subject: "GitHub Action Notification: ${{ github.repository }}"
          body: "Workflow completed with status: ${{ github.event.workflow_run.conclusion }}\nSee details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          secure: true
